version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./otelcol-config.yaml:/etc/otelcol-config.yaml
    command: [ "--config", "/etc/otelcol-config.yaml" ]
    ports:
      - "4319:4319" # OTLP gRPC (Traces)
      - "4318:4318" # OTLP HTTP
      - "9464:9464" # Prometheus metrics
    depends_on:
      - prometheus
      - loki
      - tempo

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Prometheus Web UI
    command:
      - --config.file=/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100" # Loki Log Ingestion

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200:3200" # Tempo Query API
      - "4317:4317" # Tempo OTLP gRPC (Traces)
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000" # Grafana Web UI
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - loki
      - tempo
