global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"]

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
      
  - job_name: "nodejs-app"
    static_configs:
      - targets: ["host.docker.internal:8080"]
      